apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "bohlin-dashboard"
  description: "Bohlin Dashboard used for displaying TAP relevant data in a Bokeh dashboard"
  caretakers: 
    - user:dont.mind
  tags:
    - aws
    - typescript
    - cdk
    - cicd
    - docker
    - ecs
  annotations:
    backstage.io/source-location: url:https://github.com/wojalin/DictionaryExtension/
    github.com/project-slug: wojalin/DictionaryExtension
    argocd/app-name: argo-airflow
    goharbor.io/repository-slug: airflow-plugin/airflow_local
  labels:
    hosting: aws
    runtime: container-ecs-fargate
    stages: 'y'
    pipelines: 'y'
spec:
  type: service
  lifecycle: production
  owner: "user:default/dont.mind"
